# Generated by Django 3.0.6 on 2020-05-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200515_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('username', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=3000),
        ),
    ]
