# Generated by Django 3.0.6 on 2020-05-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
