# Generated by Django 3.0.6 on 2020-05-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200525_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
