# Generated by Django 3.0.6 on 2020-05-25 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200525_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='contact',
            new_name='contactno',
        ),
    ]
