# Generated by Django 3.0.6 on 2020-05-25 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200525_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='contactno',
        ),
    ]
