# Generated by Django 3.0.6 on 2020-05-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200525_0959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
