# Generated by Django 3.0.6 on 2020-05-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200526_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='order',
            name='phone2',
            field=models.CharField(default='', max_length=20),
        ),
    ]
