# Generated by Django 3.0.6 on 2020-05-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200526_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.IntegerField(default='', max_length=20),
        ),
    ]
