# Generated by Django 3.0.6 on 2020-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.IntegerField(default=''),
        ),
    ]
