# Generated by Django 3.0.6 on 2020-05-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_order_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone3',
            field=models.CharField(default='', max_length=20),
        ),
    ]
